DirectSoundWaveData_dp_016bongo::
	.incbin "sound/direct_sound_samples/drums/dp_016bongo.bin"

	.align 2
DirectSoundWaveData_dp_053clap::
	.incbin "sound/direct_sound_samples/drums/dp_053clap.bin"

	.align 2
DirectSoundWaveData_dp_060conga::
	.incbin "sound/direct_sound_samples/drums/dp_060conga.bin"

	.align 2
DirectSoundWaveData_dp_062sleigh::
	.incbin "sound/direct_sound_samples/drums/dp_062sleigh.bin"

	.align 2
DirectSoundWaveData_dp_093snare::
	.incbin "sound/direct_sound_samples/drums/dp_093snare.bin"

	.align 2
DirectSoundWaveData_dp_808snare_16::
	.incbin "sound/direct_sound_samples/drums/dp_808snare_16.bin"

	.align 2
DirectSoundWaveData_dp_africa_dr_16::
	.incbin "sound/direct_sound_samples/drums/dp_africa_dr_16.bin"

	.align 2
DirectSoundWaveData_dp_bass2::
	.incbin "sound/direct_sound_samples/drums/dp_bass2.bin"

	.align 2
DirectSoundWaveData_dp_bassdr1::
	.incbin "sound/direct_sound_samples/drums/dp_bassdr1.bin"

	.align 2
DirectSoundWaveData_dp_bassdr1_16::
	.incbin "sound/direct_sound_samples/drums/dp_bassdr1_16.bin"

	.align 2
DirectSoundWaveData_dp_bassdr2_16::
	.incbin "sound/direct_sound_samples/drums/dp_bassdr2_16.bin"

	.align 2
DirectSoundWaveData_dp_cabassa_16::
	.incbin "sound/direct_sound_samples/drums/dp_cabassa_16.bin"

	.align 2
DirectSoundWaveData_dp_castanet_22::
	.incbin "sound/direct_sound_samples/drums/dp_castanet_22.bin"

	.align 2
DirectSoundWaveData_dp_cawbell_16::
	.incbin "sound/direct_sound_samples/drums/dp_cawbell_16.bin"

	.align 2
DirectSoundWaveData_dp_china_cynbal::
	.incbin "sound/direct_sound_samples/drums/dp_china_cynbal.bin"

	.align 2
DirectSoundWaveData_dp_closed_hihat_16::
	.incbin "sound/direct_sound_samples/drums/dp_closed_hihat_16.bin"

	.align 2
DirectSoundWaveData_dp_closehight_16::
	.incbin "sound/direct_sound_samples/drums/dp_closehight_16.bin"

	.align 2
DirectSoundWaveData_dp_cymbal1_16::
	.incbin "sound/direct_sound_samples/drums/dp_cymbal1_16.bin"

	.align 2
DirectSoundWaveData_dp_dragon_dr_16::
	.incbin "sound/direct_sound_samples/drums/dp_dragon_dr_16.bin"

	.align 2
DirectSoundWaveData_dp_handclup1::
	.incbin "sound/direct_sound_samples/drums/dp_handclup1.bin"

	.align 2
DirectSoundWaveData_dp_india_per_16::
	.incbin "sound/direct_sound_samples/drums/dp_india_per_16.bin"

	.align 2
DirectSoundWaveData_dp_kaaroop_16::
	.incbin "sound/direct_sound_samples/drums/dp_kaaroop_16.bin"

	.align 2
DirectSoundWaveData_dp_mute_conga_16::
	.incbin "sound/direct_sound_samples/drums/dp_mute_conga_16.bin"

	.align 2
DirectSoundWaveData_dp_oct_snare_16::
	.incbin "sound/direct_sound_samples/drums/dp_oct_snare_16.bin"

	.align 2
DirectSoundWaveData_dp_open_hihat_16::
	.incbin "sound/direct_sound_samples/drums/dp_open_hihat_16.bin"

	.align 2
DirectSoundWaveData_dp_openhight::
	.incbin "sound/direct_sound_samples/drums/dp_openhight.bin"

	.align 2
DirectSoundWaveData_dp_orchhitmajor60::
	.incbin "sound/direct_sound_samples/drums/dp_orchhitmajor60.bin"

	.align 2
DirectSoundWaveData_dp_orchhitminor60::
	.incbin "sound/direct_sound_samples/drums/dp_orchhitminor60.bin"

	.align 2
DirectSoundWaveData_dp_pedalhight::
	.incbin "sound/direct_sound_samples/drums/dp_pedalhight.bin"

	.align 2
DirectSoundWaveData_dp_reverscyn_16::
	.incbin "sound/direct_sound_samples/drums/dp_reverscyn_16.bin"

	.align 2
DirectSoundWaveData_dp_ridecap::
	.incbin "sound/direct_sound_samples/drums/dp_ridecap.bin"

	.align 2
DirectSoundWaveData_dp_ridecynbal::
	.incbin "sound/direct_sound_samples/drums/dp_ridecynbal.bin"

	.align 2
DirectSoundWaveData_dp_rim1_roop::
	.incbin "sound/direct_sound_samples/drums/dp_rim1_roop.bin"

	.align 2
DirectSoundWaveData_dp_sheiker::
	.incbin "sound/direct_sound_samples/drums/dp_sheiker.bin"

	.align 2
DirectSoundWaveData_dp_sne1_roop::
	.incbin "sound/direct_sound_samples/drums/dp_sne1_roop.bin"

	.align 2
DirectSoundWaveData_dp_sne2_loop::
	.incbin "sound/direct_sound_samples/drums/dp_sne2_loop.bin"

	.align 2
DirectSoundWaveData_dp_tambourine_16::
	.incbin "sound/direct_sound_samples/drums/dp_tambourine_16.bin"

	.align 2
DirectSoundWaveData_dp_tom1_16::
	.incbin "sound/direct_sound_samples/drums/dp_tom1_16.bin"

	.align 2
DirectSoundWaveData_dp_tom_16::
	.incbin "sound/direct_sound_samples/drums/dp_tom_16.bin"

	.align 2
DirectSoundWaveData_dp_triangle_16::
	.incbin "sound/direct_sound_samples/drums/dp_triangle_16.bin"

	.align 2
DirectSoundWaveData_dp_whistle_c5_16::
	.incbin "sound/direct_sound_samples/drums/dp_whistle_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_woodblock_16::
	.incbin "sound/direct_sound_samples/drums/dp_woodblock_16.bin"

	.align 2
DirectSoundWaveData_pl_musicbox62::
    .incbin "sound/direct_sound_samples/pl_musicbox62.bin"

    .align 2